feat: OPX-3.2
open-switch/opx-base-model pull request #46
Opened 2019-06-10 01:08 UTC by Tejaswi-Goel

* Update: add FEC supported port speeds
* Update: add supported port speeds for CL91, CL108 and CL74-FC
* Update: add new FEC modes to support MtEcho
* Update: base-model changes to support new media categories for Mt. Echo
* Feature: DHCP v4 and v6 Snooping support
* Update: introducing new MAC learning mode 1) os enable, hw disable
        2) os disable, hw enable for Isilon like use-cases where forwarding
        in HW takes place based on ACLs and kernel in the based on bridge MAC learning.
* Update: add the attribute to enable/disable the ARP/Nbr refresh for the HW MAC learning.
* Update: add 8x1 breakout mode for fp port - support for Mt. Echo
* Update: add profile-type attribute in port-group-state and front-panel-port list
* Update: add port-group attribute in the front-panel-port list
* Update: add profile-type attribute in port-group-state and front-panel-port list
* Update: addressed warnings and removed unused attribute.
* Update: admin attribute change to non-mandatory in the trap base model
* Bugfix: revision dates not in descending order in yang model files
* Bugfix: unable-to-apply-icmp-access-list to integration
* Update: add ICPMv6 protocol type
* Update: added support for multicast flood resrict feature
* Update: add trap_grp class for trap grp CPS support
* Update: initial proposal for NAS/NDI trap group object
* Update: add 80g speed and new 8x10, 2x40 media
* Bugfix: add new hashing algo to fix user data traffic not load balanced, leading to
        over utilization of links
* Feature: initial checkin telemetry CLI enhancement

Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

2019-06-12 16:48 UTC, Tejaswi-Goel commented
Pull-request updated, HEAD is now 7e89cc4d8556b641a1547290c6835700ef9c64f1

2019-06-17 19:22 UTC, rakeshdatta requested changes

2019-06-17 19:22 UTC, rakeshdatta commented on yang-models/dell-base-cleanup-events.yang
> +        Copyright (c) 2015-2018 by Dell EMC, All rights reserved.";
Change the copyright

2019-06-17 19:22 UTC, rakeshdatta commented on yang-models/l3-multicast.yang
> +                 Copyright (c) 2015-2018 by Dell EMC, All rights reserved.";
copyright!

2019-06-17 19:31 UTC, Tejaswi-Goel commented
Pull-request updated, HEAD is now ac810954cda2d1380efa7d4d167b22dfa2ff6aca

2019-06-17 21:43 UTC, Tejaswi-Goel commented
Pull-request updated, HEAD is now 2758218e3afbcce22a15139a57d37a48b2bbd643

2019-06-17 22:50 UTC, hpersh approved these changes

2019-06-18 00:41 UTC, rakeshdatta approved these changes

2019-06-18 18:41 UTC, merged